package-lock.json
src/pages/processes.md

Foreslår at denne legges åpent? Og da kanskje at diskusjonen på den kan gå her. 
Må selvsagt fortsatt implementeres i Trello, det er en svakhet med to sannheter.

Tenker at onbording-prosessen godt kan være public

---

src/pages/processes.md

Lagt til en kort setning om at Variant ikke tillater opparbeidelse av bonuspoeng

Bonuspoeng

---

src/pages/processes.md

Fikser stavefeil

---

src/pages/handbook.md

Vi burde ha en tekst om hvordan ammefri fungerer. Her forholder vi oss til hvordan arbeidsmiljøloven er.
1. Ammende mødre har rett til 1 time lønnet fri hver dag til amming
2. De kan ta den når de selv vil og hvordan det passer inn med deres hverdag.
Flere detaljer: https://www.arbeidstilsynet.no/arbeidsforhold/permisjoner/foreldrepermisjon/ammefri/
Jeg tror vi må iterere litt på teksten, og jeg er ikke helt sikker på om Arbeidstid er den beste plassen å ha teksten under.

Oppdaterer arbeidstid med tekst om ammefri

---

README.md
package-lock.json
package.json

- Oppdaterer avhengigheter (sikkerhets issue).
- Bumper versjon for npm pakke.
- Fikser kodeeksempel for programatisk bruk.

Generell vedlikeholdsoppdateringer

---

.prettierignore
package-lock.json
src/layout.html
tools/generate.js

Utvider genereringsscriptet til å inkludere en navigasjonsmeny for sider (håndbok, prosesser og kvalitetshåndbok).
Helt enkel meny. Burde revurderes til sin egen stil om redesign av håndboken.

Legger til en enkel navigasjonsmeny på venstresiden for navigering av sider

---

src/pages/handbook.md

I #22 ble fil og URL endret. Oppdaterer lenker til å peke til ny side.

Fikser feil i lenker etter rename av processes

---

src/pages/information.md

Utkast til enkel tekst som lenker til gadgetoversikt for eksempler.

Utgiftsføring av gadgets

---

src/pages/handbook.md

Tenker dette kan selskapet tjene på, og den ansatte kan tidvis gjøre bedre bruk av sine budsetter

Bruk av gadget til spons

---

src/pages/handbook.md

Prøver likevel å se om det passer inn i håndboka. Dette avsnittet bør få selskap om hva vi merner angående emisjonsrunder for de ansatte som vi løst snakker om skal komme en gang,.

WIP Forslag til tekst ang medeierskap

---

src/pages/handbook.md
src/pages/information.md

Endrer fra gamle Digs til nye Digs.

Oppdaterer adressen til kontorene våre

---

src/pages/handbook.md

ref samtale på Slack - #sommerfest2019.

Tatt bort sommerfest

---

.github/spellchecker.yml

Legger til config for installert Probot som sjekker skrivefeil. Utviklet her: https://github.com/varianter/probot-spellchecker
Tenker vi kan prøve denne ei stund, og se om det gir noe verdi?

Add spellchecker config

---

src/pages/quality_manual.md

Etablering og formalisering av alle faste sosiale aktiveter vi har som en del av interne rutiner. Noe som mangler, @varianter/sosialkomite ?

Legger til informasjon om faste sosiale aktiviter

---

src/pages/information.md

Ser dette rett ut, @adriansberg?

Fikser døde lenker under mobilskifte og reiseregning som rapportert i #56

---

src/pages/handbook.md

Kortade ned flera avsnitt i handboken. Tog bort ett i sin helhet. Ändrade några för att bli mer to-the-point. 
Givet mitt modersmål så är det säkerligen några fel i texten. ;D

Kortade ned texten i handboken en aning.

---

src/pages/handbook.md

Etter den store endringen i går så måtte jeg fikse på et par typos når jeg så de.

Småfiks her og der

---

src/pages/information.md
src/pages/quality_manual.md

Ref tidligere avgjørelser om eget fond for sosiale aktiviteter. Rent konkret "bevilgning" til hytteleie i Åre. Beskriver hva det er, hva det er tenkt til og hvordan man skal gå frem. Også lagt til som beskrivelse i kvalitetshåndboka.

Legger til forslag om sossis-fond i håndboken

---

src/pages/information.md

Dette er bare et forslag til passende nyere alternativer 🙂

Fiks døde lenker til laptoper :computer:

---

src/pages/information.md

Oppdatert råd for mistanke om alvorlig sykdom eller koronavirus-smmitte.

Oppdatert sykmeldingsråd

---

src/pages/information.md

Lagt til informasjon om epost for varsling av sykemelding

rutine for innrapportering av sykmelding

---

src/layout.html
src/static/styles/style.css

Fixes #95 
Legger til det simpleste søket jeg kan komme på som fortsatt kan gi verdi.

Adds simple Google Custom search

---

src/pages/information.md

Telia har kommet med verktøy for å bytte som gjør det enklere uavhengig om man selv er juridisk ansvarlig eller om et annet selskap er det.

Forenkler beskrivelse om eierskifte for Telia

---

src/pages/handbook.md
src/pages/information.md

La til informasjon om sykkelparkering. Stort sett samme info som Tonje har postet på Slack.

informasjon om sykkelparkering

---

src/pages/information.md

Det er mulig avsnittet om ekstern lån (community) egetlig bør ligge i selve håndboka?

Avsnitt om utlån

---

src/pages/quality_manual.md

Databriller

---

src/pages/quality_manual.md

Lagt til kort info om temperaturmålinger.

Winningtemp

---

src/pages/information.md

Oppdatert tekst om klimafotavtrykk under reiseregning litt.

Klimafotavtrykk

---

.vscode/settings.json
content/handbook.md
content/information.md
content/quality_manual.md
content/variantdag.md
pages/[handbook].tsx
pages/[handbook]/[name].tsx
pages/api/search.tsx
pages/index.tsx
pages/search.tsx
src/components/book/index.tsx
src/layout/index.tsx
src/layout/layout.module.css
src/search/index.tsx
src/utils/index.tsx

- Show pages in the header
- Add the possibility for nested handbooks

feat: Add possibility for nested handbooks

---

content/variantdag.md

@varianter/fagkom-trh Sjekk ut her

Legger til tekst om Fagkomité under Variantdag-håndbok

---

content/avdelinger/oslo.md
content/avdelinger/trondheim.md
src/app.css

- style: Change typography for h3 and h4
- Flytt om på lokasjoner

Typografiendringer

---

src/layout/index.tsx

fix: issue with subpage slug generation. fixes #147

---

content/avdelinger/trondheim.md

Vi bruker da vel ikke Sharepoint vi?

Dokumenter ligger på ... docs

---

.gitignore
content/information.md

Da det har kommet nye versjoner av macbooks og Lenovo PCer trenger vi å oppdatere mest populære modeller i håndboka. Legger også til .idea mappa i gitignore for de som bruker intellij for editing av prosjektet.

Oppdater PC og Mac modeller og legg til til .idea i .gitignore

---

content/information.md

Gammel utdatert lenke. Fant tilsvarende 👍 
Mener hele "kapittelet" er relevant her, så jeg lenka et nivå lengre ut.

Update outdated skatteetaten link

---

content/information.md

Legger til notis om oppdatering av kontaktinfo under portering av telefon. Løser https://trello.com/c/4TMEQP5l/341-legge-til-info-om-kontaktinformasjon-i-onboarding-h%C3%A5ndbok

feat: adds info on contact info phone

---

content/information.md

Gjorde noe formatering samtidig her, men det viktige er her: https://github.com/varianter/handbook/pull/170/files#diff-95d11520ab15f1a31e742c453897e0825c9dfa15071d75cfa5f517632bca5339R79

Adds note on HV and mil service. Fixes #126

---

content/avdelinger/oslo.md

Replace Spaces with Tollbugata 24 here:
- Sykkelparkering
- Lokalt HMS-arbeid
- Branninstruks
- Kildesortering

Replace Spaces with Tollbugata

---

content/avdelinger/oslo.md

Update wifi information in oslo.md

---

content/information.md

Oppdatert lenke til gadgetbudsjett i "Nyttige lenker"

Oppdatert lenke til gadgetbudsjett

---

content/handbook.md

Har gått gjennom tekstene i ledig stund og foreslår mindre endringer.  Har også oppdatert innhold rundt
-  årlig varianttur
- Oppdatert Variantdag til også å omtale felles variantdag
- Oppdatert lenke til gadget til å gå mot dash.

Språkgjennomgang og noen innholdsoppdateringer

---

content/information.md

Behov for å følge opp på egenmeldinger som har stor fravær for tiden. Notis i håndbok om prosess for varsling av egenmelding til nærmeste leder.

adds note on egenmelding

---

pages/information.mdx

Setningen som beskriver slack er litt "cocky". Endrer denne til noe mer folkelig og forståelig.

Endre beskrivelse av Slack som verktøy

---

pages/information.mdx

Energi.ai er løsningen alle selskaper i Variant tester ut for automatisert karbonregnskap. Alle ansatte vil om kort tid få tilgang til systemet slik at alle kan være live oppdatert på vår påvirkning på miljøet.

Lagt til link til energi.ai

---

.gitignore
package.json
pages/search.tsx
src/components/illustrationList/index.tsx
src/components/pageSelector/index.tsx
src/layouts/general/index.tsx
yarn.lock

Updates all dependencies to latest. Seems to still be working as expected.

chore: updates dependencies

---

pages/avdelinger/bergen.mdx
pages/avdelinger/oslo.mdx
pages/avdelinger/trondheim.mdx
pages/prosesser-ansatt.mdx
pages/prosesser-avtaler.mdx
pages/prosesser-baerekraft.mdx
pages/prosesser-hms.mdx
pages/prosesser-ledelse.mdx
pages/prosesser-mangfold.mdx
pages/prosesser.mdx

Legger til første utgave av ledelsesoversikt. Først for å skrive ned folk og roller, men etterhvert kan dette utvides til å skrive om ledelsesplattform og rutiner i ledelse.

feat: adds processes page for managemet

---

pages/avdelinger/bergen.mdx

Oppdatert Bergen-info siden vi ikke lengre er på Spaces.

Endret lokasjon i Bergen fra Spaces til Vaskerelven 39

---

src/layouts/general/layout.module.css

Lagt til en scrollbar som har lik bakgrunn som navbar

fix: show scrollbar webkit

---

src/app.css
src/layouts/general/index.tsx
src/layouts/general/layout.module.css

Bakgrunnen vil nå dekke hele bredden på siden

fix: dark background on large screens

---

src/layouts/handbook/index.tsx

Lagt til id for at man skal kunne referere til siden på søk

fix: H4 now have a id for search

---

.github/workflows/indexer.yml

fix: Only index if markdown-page has changed

---

pages/index.mdx
src/components/navbarLinks/checkIfHeadingShouldBeRemoved.tsx
src/components/navbarLinks/navbarLinks.tsx
src/components/navbarLinks/navbarLinksMobile.tsx
src/types/toc.d.ts

Mulighet til å fjerne enkelte headings fra navbaren, men kan fortsatt bruke h3

fix: h3 between h2 and h4

---

pages/avdelinger/oslo.mdx

- Added arbeidsmiljøutvalgets representanter
- Added ansattrepresentant
- Updated Verneombud
[preview](https://handbook-q297ovymg-variant1.vercel.app/avdelinger/oslo)

fix: updated roles and added new roles to Oslo office

---

pages/avdelinger/oslo.mdx

Som et tiltak for å begrense utslippene våre, både i matveien, men også restavfall, informerer bærekraftsgjengen om nye rutiner for å gjøre valg av matbestilling lettere til arrangementer.

Ny info om rutiner for mat på arrangementer i oslo.mdx

---

pages/information.mdx

Oppdaterer tall om gadget ved utkjøp eller fratredelse i henhold til forskriften om takseringsregler for inntektsåret 2022

fix: adds note on over 3 years

---

pages/information.mdx

Et forsøk på å beskrive rutiner rundt overføring av ferie, og hvordan tolke ferieloven.

Legge til tekst om overføring av ferie

---

pages/information.mdx

Etter forslag fra @astride, mer tydelig veiledning på hvordan ferie fungerer.

feat: legger til eksplisitt tekst om ferietid

---

pages/avdelinger/oslo.mdx

Lägger till info om rabatter genom Nordea Liv Pluss

feat(oslo): add nordea discount

---

pages/avdelinger/oslo.mdx
pages/prosesser-baerekraft.mdx

feat: change sustainability goals heading
